githubuser0xFFFF/Qt-Advanced-Docking-System

- demo/MainWindow.h
- src/DockAreaWidget.h
- src/DockContainerWidget.h
- src/DockManager.h
- src/DockOverlay.h
- src/DockSplitter.h
- src/DockWidget.h
- src/DockWidgetTitleBar.h
- src/FloatingDockContainer.h
- src/ads_globals.cpp
Number of warnings like this has been fixed
```
DockWidget.h:62:9: warning: class 'DockContainerWidgetPrivate' was previously declared as a struct [-Wmismatched-tags]
```
Also in `ads_globals.cpp` Clang didn’t like how that code setup so I changed it to what I think is the correct way. This would be good to get verified.
> Compile and warning fixes for macOS

- src/DockWidget.cpp
When i figure out, how to delete widgets after closing tabs. I took gamma ray from kdab and started to monitor what happens when I open and close the tabs. At some point, I noticed that there are some dangling QActions. Fortunately, the problem was solved simply, when creating a new DockWidget, a QAction is created which is responsible for showing / hiding the tab, which was constructed with nullptr to parent, and the object was not deleted in the destructor. Therefore, this QAction remained in memory.
> Fix of action leak in CDockWidget

- .gitignore
All JetBrains IDEs create a .idea folder in the project root that is local to the system/user and should not be included in a repository.
> Add .idea folders to .gitignore

- CMakeLists.txt
I had trouble including this project as part of a bigger CMake build until the quotes were added. This is only an issue because `${ads_INCLUDE}` is a list. Relevant SO [answer](https://stackoverflow.com/a/44430690)
#46
> fix: Add quotes to CMake BUILD_INTERFACE generator

- src/ElidingLabel.cpp
QFontMetrics::width() has been deprecated. Using QFontMetrics::horizontalAdvance() is the proper way to go (introduce in Qt 5.11).
> Replace deprecated function call to QFontMetrics::width()

- src/DockContainerWidget.cpp
When adding new DockWidget directly to a floating container using `addDockWidgetTabToArea`, the title bar is hidden until title bar is updated in some other way. This should cause title bar to always update.
> Update floating widget titlebar visibility after adding new tab

- CMakeLists.txt
- adsConfig.cmake
This is example CMake configuration for Find support. It allows using this library by simply using 
```
find_package(ads REQUIRED)
...
target_link_libraries(${PROJECT_NAME}
ads::QtAdvancedDockingSystem
)
```
This should work out of the box on Linux with global installation and on Windows after adding `$INSTALL_LOCATION/lib/cmake/ads` to CMAKE_PREFIX_PATH.
If you want to change any naming, feel free to base on this commit.
> Add support for CMake Find config module

- src/ElidingLabel.cpp
`ADS_STATIC` and `ADS_SHARED_EXPORT` are used in the public API and must therefore be `PUBLIC`. Currently the `ADS_EXPORT` macro in `ads_globals.h` is set to `Q_DECL_IMPORT` instead of being empty which makes it impossible to link statically.
> Fix cmake when compiling to a static lib

- PyQtAds/QtAds/__init__.py
Without the fix, importing from the installed python module results in the following error:
```
>>> from PyQtAds.QtAds import CDockWidget                                                                                                                                                                                       
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-9ff2e5d03daf> in <module>
----> 1 from PyQtAds.QtAds import CDockWidget
~/tmp/Qt-Advanced-Docking-System/build/lib.linux-x86_64-3.8/PyQtAds/QtAds/__init__.py in <module>
1 from .ads import ads
----> 2 from ._version import *
3 
4 import inspect
5 
ModuleNotFoundError: No module named 'PyQtAds.QtAds._version' …
```
> Fix import in QtAds.__init__.py

- src/DockAreaTabBar.cpp
Regression introduced by 29ebc83b351932598ae83f47205c4d09bb852b47
> Fix tabs not being active when restoring state

- demo/MainWindow.cpp
- src/DockAreaWidget.cpp
- src/DockAreaWidget.h
- src/DockContainerWidget.cpp
- src/FloatingDockContainer.cpp
- src/FloatingDragPreview.cpp
Following issue https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/issues/104
This change allows setting DockAreas per individual DockAreaWidget. By default, all areas are allowed to maintain backward compatibility.
> setAllowedAreas for individual DockAreaWidget

- README.md
- demo/MainWindow.cpp
- src/DockAreaTitleBar.cpp
- src/DockManager.cpp
- src/DockManager.h
When this flag is set disabled dock area buttons will not appear on the tollbar at all (enabling them will bring them back)
(This serves not just "CentalWidget" purpose but to me seems to be a generally possible user preference)
> Added DockAreaHideDisabledButtons configuration flag

- src/DockManager.cpp
- src/DockManager.h
This allows to subscribe to events of the newly created window.
A common use case is to show a message box if a dock container with many modified documents in it is closed. This allows for the user to decide whether he wants to save / discard all the changes or cancel the closing of the window.
> Added CDockManager::floatingWidgetCreated event

- sip/DockContainerWidget.sip
- sip/DockOverlay.sip
- sip/DockSplitter.sip
Fixes building for 3.2.4:
* Adds CDockAreaWidget argument
Adds missing bindings for:
* CDockOverlay::visibleDropAreaUnderCursor
* CDockSplitter::firstWidget
* CDockSplitter::lastWidget
@githubuser0xFFFF, would you allow an addition to the Travis CI configuration to build the Python bindings on each commit? It could be made `xfail` such that it doesn't get in the way of your development, but it could also give us (@n-elie and @hhslepicka) a heads-up when we need to fix it.
> FIX: DockContainerWidget::dropWidget API change not reflected in Python bindings

- src/FloatingDockContainer.h
A memory leak is caused by missing the virtual destructor in IFloatingWidget.
> Fix memory leak

- examples/sidebar/MainWindow.h
- examples/simple/MainWindow.h
- src/DockAreaTitleBar.h
- src/DockAreaWidget.h
- src/DockContainerWidget.h
- src/DockManager.h
- src/DockOverlay.h
- src/DockWidget.h
- src/ads_globals.h
Qt classes should be forward declared with QT_FORWARD_DECLARE_CLASS, because some builds of Qt declare everything inside a namespace.
> Support for Qt built with the -qtnamespace configure option

- src/DockContainerWidget.cpp
`CDockContainerWidget::removeDockArea` currently checks if `std::find` returns `nullptr` – that should never be the case, it returns `last` if the element was not found. Because of this, `LastAddedAreaCache[5]` might get overwritten, which is out of range.
> Fix Undefined Behavior in LastAddedAreaCache

- src/FloatingDockContainer.cpp
- src/FloatingDockContainer.h
- src/linux/FloatingWidgetTitleBar.cpp
- src/linux/FloatingWidgetTitleBar.h
Continuation from #228
I switched back to using `showNormal` and Co. This simplified the code by a good bit and also allows to benefit from possible future updates in QTs `showNormal` and especially `showMaximize` functions.
Everything seem to be fine, but further tests especially on other window manager might be a good idea.
*Fixed from last state:*
- *Restoring maximized windows now works properly.*
- *Maximized window size should no be more often correct. (QT itself uses workarounds to get this playing nice with X11)*
The only thing i am not really sure about is that i had to remove `setAttribute(Qt::WA_X11NetWmWindowTypeDock, true);` because that broke `showMaximized` for some reason.
I don't see any change on my System tho, but this may be different on other systems .?
> Add maximize button to FloatingWidgetTitleBar [Revived 2]

- src/DockAreaWidget.cpp
Or they will never be deleted.
> Delete widgets without parents in CDockAreaLayout.

- src/DockAreaWidget.cpp
- src/DockAreaWidget.h
- src/DockWidget.cpp
- src/DockWidgetTab.cpp
Changes the state of the close button on titlebar and tabbar after the CDockWidget has already been added.
> Update the state of close button.

- src/DockAreaWidget.cpp
- src/DockManager.cpp
- src/DockWidget.cpp
* DockWidget always has DockAreaWidget as parent. It's not necessary to make it nullptr. This fixes many bugs related to restoring inactive tabbed DockWidgets.
* Fixed memory leaks related to QBoxLayout::takeAt().
* Fixed algorithm of deleting remaining floating widgets after restore.
Sorry for the pack. I don't have much time to make it in three different pull requests.
There were several commits recently that roughly delete DockWidgets if there is no parents, so they can be avoided, after this fix.
> Fixes pack. Parenting, memory leaks, floating widgets deleting.

- src/DockFocusController.cpp
- src/DockManager.cpp
- src/DockManager.h
- src/FloatingDockContainer.cpp
- src/FloatingDockContainer.h
- src/ads_globals.cpp
- src/ads_globals.h
- src/linux/FloatingWidgetTitleBar.cpp
- src/linux/FloatingWidgetTitleBar.h
- src/src.pro
Ok, three times is the charm.
This is a combination of PR #228 and #230
Since i did not found a way around the issue that KDE doesn't seem to send move event WHILE moving but only once when the moving is finished, i jumped back to using the custom titlebar and using a Qt::Window type.
We are still extending from Qt:DockWidget but just to borrow their resizing behavior.
To hide the Window from the task bar i had to directly communicate with the Xserver because Qt for some reason doesn't support this by itself ( see https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/pull/230#issuecomment-668870767 ).
This means the x11extras qt module is now required under linux. 
Tested under latest Ubuntu and Kubuntu LTS, Mate, XFCE and openbox.
There are still some minor quirks on some window …
> Add maximize button to FloatingWidgetTitleBar

- src/stylesheets/default.css
- src/stylesheets/default_linux.css
- src/stylesheets/focus_highlighting_linux.css
The stylesheet should only change the style of ads::CDockSplitter
instances, but not all QSplitter instances. Otherwise all splitters
within any dock widget will also be affected and look different from
the default Qt style.
> Ensure that the stylesheet doesn't affect all QSplitter instances

- src/DockManager.cpp
- src/DockManager.h
Add the ability to programmatically update splitter sizes. The user must
specify the dock area that is contained in a splitter and a list of
sizes. The list of sizes will be passed to the splitter that immediately
contains the specified dock area. If the dock area is not part of a
splitter the method will have no effect.
> DockManager: add the ability to programmatically update splitter sizes

- src/DockFocusController.cpp
It is possible to create a `setFocus()` recursion under the following conditions:
CDockManager::FocusHighlighting = true
CDockManager::eConfigFlag::AllTabsHaveCloseButton = true
CDockManager::eConfigFlag::TabCloseButtonIsToolButton = true
with one dock widget set as the central widget and the other docks tabbed in the same area.
Reproduced with `CentralWidgetExample`:
> Prevent setFocus() recursion when application focus changes.

- src/src.pro
There are some non-ASCII characters "…" in ElidingLabel.cpp(default UTF-8 No Bom), and this will cause building error with msvc in some windows systems like mine(the default character-encoding is gbk).
`> chcp `
`Active code page: 936`
Adding utf-8 support for msvc can resolve this building error.
> Add utf-8 support for msvc to resolve building error in some windows systems.

- src/CMakeLists.txt
Continue #277 for cmake. 
I'm not familiar with cmake, so I just do this work according to [stack overflow](https://stackoverflow.com/questions/47690822/possible-to-force-cmake-msvc-to-use-utf-8-encoding-for-source-files-without-a-bo) and test passed.
> Add utf-8 support for msvc within cmake.

- src/DockContainerWidget.h
- src/DockManager.h
- src/DockWidget.h
- src/FloatingDockContainer.h
This allows Qt Advanced Docking system to be compiled with the QT_NO_KEYWORDS definition. This can help avoid conflicts with other dependancies for a project.
For example, boost::signals.
> Removes reliance on special Qt keywords.

- demo/CMakeLists.txt
- examples/centralwidget/CMakeLists.txt
- examples/deleteonclose/CMakeLists.txt
- examples/dockindock/CMakeLists.txt
- examples/emptydockarea/CMakeLists.txt
- examples/sidebar/CMakeLists.txt
- examples/simple/CMakeLists.txt
- src/CMakeLists.txt
Hey!
I noticed there was no Qt6 support on the CMake version of the build system. I added it!
Thanks again for your great work!
> Add Qt6 support on CMake

- src/DockWidgetTab.cpp
When changing the tooltip of the tab the icon label tooltip was not updated, but the tooltip of the text was.
This is a super minor change that fixes it.
> Update icon label tooltip when the tab tooltip changes

- src/DockOverlay.cpp
Another tiny change.
`QString::SkipEmptyParts` was marked for deprecation in Qt5.15. This removes the warning.
Since `Qt::SkipEmptyParts` was added in 5.14.0 I just check for that.
> Remove deprecation warning while building with Qt5.15

- sip/ads_globals.sip
The loop in findParent stopped too soon
> Python Bindings: Fix findParent that was not working as expected

- src/DockContainerWidget.cpp
- src/FloatingDockContainer.cpp
- src/FloatingDockContainer.h
See https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/issues/351
Hide the floating dock container when the widget has been redocked without hiding the contained widget
> Fix issue #351

- src/DockWidgetTab.cpp
This fixes a bug where, if `CDockManager::MiddleMouseButtonClosesTab` is enabled, you could close a dock widget by middle-clicking its tab even if its `CDockWidget::DockWidgetClosable` flag is set to `false`.
> Prevent middle-click from closing unclosable tabs

- src/DockContainerWidget.cpp
This fixes a crash which could occur when restoring the state of a floating container to a non-floating container.
This was because `ads::CDockContainerWidget::RestoreState()` will unconditionally assume this is floating if the XML has the `Floating` boolean set, and will dereference `floatingWidget()`. If this isn't floating, `floatingWidget()` will return `nullptr`, leading to a crash when it's subsequently used.
Fixes #379.
> Fix potential crash when restoring container state

- CMakeLists.txt
The main CMakeLists.txt was updated to allow explicitly setting the
version for the project by setting the `ADS_VERSION` variable (e.g.
cmake .. -DADS_VERSION=1.0.0).
The default behavior is to determine the version by reading the
information from git. Adding the option to override this variable at
configure time allows the library to be built outside of its git
repository, such as when the code is vendored directly into another
project and added using `add_subdirectory`.
See #352
> CMake: Allow version to be explicitly set without requiring git

- src/DockContainerWidget.cpp
- src/stylesheets/default.css
- src/stylesheets/default_linux.css
- src/stylesheets/focus_highlighting.css
- src/stylesheets/focus_highlighting_linux.css
Currently the DockContainerWidget sets a content margin of 0,1,0,1 (top and bottom) and since it is not possible in QT to influence layouts via stylesheets this leads to issues with custom stylesheets.
See: https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/master/src/DockContainerWidget.cpp#L1289 
This PR removes the content margin set in code and replaces it with padding to the child QSplitter instead.
This should behave the same as before (when using the default stylesheets) but allows to get rid of it if required.
> Removed ContentMargin in DockContainerWidget

- src/DockManager.cpp
- src/DockManager.h
Fixes #394, by implementing a method that I suggested there.
This adds a `addDockWidgetToContainer()` method to `CDockManager`, which allows a dock widget to be registered with the dock manager, and added to a specific container, even if that container doesn't currently have any `DockAreaWidget`s.
This is pretty much just a clone of `addDockWidget()`, but with the ability to specify a container widget instead of a dock area.
> Add method to add dock widget to dock container

- src/FloatingDockContainer.cpp
- src/FloatingDockContainer.h
fix(issue-350): on RedHat/CentOS, sometimes there will be one more move event after user release their mouse which will cause the floating overlay can not be hide. Here we use the WindowActivate and WindowDeactivate event to check whether user release their mouse.
> fix centos stuck issue

- src/DockManager.cpp
Avoid calling XCB functions under non-XCB platform like Wayland, the application stop suddenly if a xcb function is used.
Yes, I know that docks does not work perfectly under Wayland (non-XWayland).
> Avoid calling XCB functions under non-XCB Linux platform

- src/CMakeLists.txt
- When linking the library as **imported target** (e.g. using vcpkg) it will link it against the name `ads::qtadvanceddocking`, because we exported it in `ads::` namespace. 
- But when linking the library **as subdirectory** (e.g. using CMake FetchContent), we would link it with `qtadvanceddocking`, without namespace.
It's a common practice to add CMake ALIAS target to fix this.
Adding alias fixes this, so you always link the target with common `ads::qtadvanceddocking`, regardless the target type.
1. Changed path to license source files using `CURRENT_SOURCE_DIR`. This is needed when adding the library to the project as subdirectory.
2. Changed license destination path to `license/ads`, to prevent different libraries licence overwrite.
> CMake bugfixes [target alias, license install]

- src/DockAreaWidget.cpp
- src/FloatingDockContainer.cpp
This fixes an issue where the feature `DockWidgetDeleteOnClose` must be set in order for the feature `CustomCloseHandling` to function properly.
> fix CustomCloseHandling depending on DockWidgetDeleteOnClose

- src/CMakeLists.txt
Qt6 requires C++17 for building and for being used as part of a project. ADS however only requires C++14 so far. Now when building using Conon for example the packages are built independently and ADS is built using the C++-14 flag which in turn causes the included Qt6 headers to fail the compile process. This patch bumps the required C++ standard to C++17 for builds targeting Qt6 only.
For example this is  part of the output when building with Conan against Qt6 without the provided patch (sorry for the color-escapes trouble):
> -- Generating done
> -- Build files have been written to: /home/user/.conan/data/qt-advanced-docking-system/3.8.2/_/_/build/05d8c98cf4a7dcaed67ebc1c04d0a853dadeab36
> [  4%] Automatic MOC for target qtadvanceddocking
> [  4%] Built target qtadvanceddocking_autogen …
> Set required C++ standard depending on Qt version

- src/CMakeLists.txt
Qt6 compatibility is broken in some cases when building with conan. This is due to the find_package version check against 5.5 rejecting the Qt6 version (e.g. 6.3.1).
For example this is a possible output which we are currently facing on the Conan Center CI:
> CMake Error at src/CMakeLists.txt:4 (find_package):
>   Could not find a configuration file for package "Qt6" that is compatible
>   with requested version "5.5".
> 
>   The following configuration files were considered but not accepted:
> 
>     /home/conan/w/prod/BuildSingleReference/.conan/data/qt-advanced-docking-system/3.8.2/_/_/build/fe39716ce00f0da6fc16495bd074b5a38407e58e/Qt6Config.cmake, version: 6.3.1
One option is to remove the version check altogether as proposed with this patch. The version check allowed versions …
> Remove version check for qt 5.x to fix conan qt6 compatibility

- src/CMakeLists.txt
As suggested here: https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/issues/270#issuecomment-717178889
I was unable to build using the LLD linker before adding this, getting the same "undefined reference to xcb_*" errors.
> Add link to xcb library on Linux

- src/DockFocusController.cpp
We have the following scenario:
- Two main views, one with the ADS, one without
- The second view can delete widgets displayed by the ADS in the first view
=> Open two widgets, focus the one you're about to delete
=> Change view, delete widget (which calls `takeWidget()` + `closeDockWidget()` from ADS), come back to ADS view
=> Crash inside `CDockFocusController::onDockWidgetVisibilityChanged` because `d->OldFocusedDockWidget` points to deleted memory
This MR fixes this by using a QPointer so when the event is called, `d->OldFocusedDockWidget` is `nullptr`.
> fix: DockFocusController doesn't pick up on old dock deletion outside of view

- doc/user-guide.md
- src/DockManager.cpp
- src/DockManager.h
- src/FloatingDockContainer.cpp
Allow to set a custom title for all FloatingContainer that does not reflect the title of the current dock widget rather than directly falling back to `QGuiApplication::applicationDisplayName()`.
> Allow to set a custom title for all FloatingContainer

- demo/CMakeLists.txt
- examples/autohide/CMakeLists.txt
- examples/centralwidget/CMakeLists.txt
- examples/deleteonclose/CMakeLists.txt
- examples/dockindock/CMakeLists.txt
- examples/emptydockarea/CMakeLists.txt
- examples/hideshow/CMakeLists.txt
- examples/sidebar/CMakeLists.txt
- examples/simple/CMakeLists.txt
- src/CMakeLists.txt
This PR is to make Qt-Advanced-Docking-System linked with Qt6 and Qt5 coexists.
I am trying to add Qt-Advanced-Docking-System ad PySide bindings to conda-forge : https://github.com/conda-forge/staged-recipes/pull/22004
The PyQt bindings is already [there](https://github.com/conda-forge/pyqtads-feedstock) but ads is built statically and only with Qt5 version.
So, I would like to make a separate package for ads that can be a dependency of both PyQt and PySide bindings, with bindings for Qt6 and Qt5. We would end with 5 packages: `qt-advanced-docking-system`, `pyqtads` (for Qt5), `pyqt6ads` (for Qt6), `pyside2qtads` (for Qt5) and `pyside6qtads` (for Qt6).
Regards
> Change targets name based on Qt version

- src/CMakeLists.txt
Fix wrong include path in CMake install introcuded in #489
> Fix wrong include path in CMake install

- src/DockAreaTitleBar.cpp
- src/DockManager.h
Hi, @githubuser0xFFFF, hope you are doing well :). This is is a small QOL PR for the auto hide dock. I noticed that some users don't understand the distinction between closing an auto hide dock and collapsing an auto hide dock. This leads to situations where they press the close button (losing the side tab widget) instead of simply clicking outside the auto hide dock (collapsing the dock). 
Therefore, I added a config so that pressing the close button would simply collapse the auto hide dock instead of hiding it. 
Here's the new behavior:
And the old behavior:
> Add config to make close button collapse auto hide dock

- src/DockAreaTabBar.cpp
- src/DockAreaWidget.cpp
- src/FloatingDockContainer.cpp
Sometimes the synchronous calculation of the rectangular area fails
> a few bugs

- src/AutoHideSideBar.cpp
- src/AutoHideSideBar.h
Hi @githubuser0xFFFF. Thanks for merging #524, this is just a small addition to that. During restore, the entire dock manager state is hidden, so `isVisible` does not return the correct state (It thinks all the tabs are hidden in the sidebar, when actually the entire window is just hidden during restore). There's two possible fixes for this, ignore the hideEvent during `restoreState`, or simply check the visibility to the parent. I opted for the latter fix since I can see you are already listening to the `ShowToParent` event.
Thanks!
> Bug fix sidebar state during restore

- src/CMakeLists.txt
This fixes linking of the XCB library on FreeBSD.
Based on my CMake knowledge I do think that the same technique should be used for other platforms too (the use of `find_package(X11)` together with linking to the corresponding `X11::xcb` target). However, I did not want to modify anything existing to prevent breaking something I'm unaware of.
> Fix CMake scripts for FreeBSD

- src/AutoHideTab.cpp
Hi @githubuser0xFFFF, hope you are doing well 😄 
Here's a bug fix for a small crash that I found.
**How to reproduce:**
1. In `AdvancedDockingSystem::MainWindow`, add `CDockManager::setAutoHideConfigFlag(CDockManager::AutoHideSideBarsIconOnly);`
2. Pin a dock that has an icon (Ensure that it's pinned to the left or right side)
3. Try to drag it out into its own window
4. Observe that it crashes on `CAutoHideTab::mouseReleaseEvent` -> `				 d->DockWidget->autoHideDockContainer()->resetToInitialDockWidgetSize();` because autoHideDockContainer is nullptr 
**Fix**
The crash can actually happen with non icon only tabs, but is masked by the orientation check, this is why it doesn't happen normally.
Fix: Check if auto hide container exists first on mouse finish dragging event.
> Fix crash in auto hide tab

- CMakeLists.txt
When targeting msvc, in static builds, unable to specify [CMAKE_MSVC_RUNTIME_LIBRARY](https://cmake.org/cmake/help/latest/variable/CMAKE_MSVC_RUNTIME_LIBRARY.html), because the policy [CMP0091](https://cmake.org/cmake/help/latest/policy/CMP0091.html#policy:CMP0091) is not set. It has to be set to NEW (defaults to OLD), and its default value is already deprecated anyway. This commit is a quick fix for that.
> Enabled modifying MSVC runtime in cmake

- demo/status_dialog.py
- examples/autohide/main.py
- examples/centralwidget/main.py
- examples/deleteonclose/main.py
- examples/dockindock/dockindock.py
- examples/dockindock/dockindockmanager.py
- examples/dockindock/main.py
- examples/dockindock/perspectives.py
- examples/emptydockarea/main.py
- examples/sidebar/main.py
- examples/simple/main.py
- pyproject.toml
- sip/ads.sip
Hi!
The following patch does a few things:
- Reduce requirements for the python build.
- Fix version number in pyproject.toml.
- Generate type hints for *.pyi files.
- Makes the project functional for sip-build
- Reduced the unnecessary depth of the package.
NOTE: This is a breaking change for python users, where, `from PyQtAds import QtAds` is changed to `import PyQtAds as QtAds`( or simply `import PyQtAds`)
Please let me know if this looks good.
Thanks,
Nate
> Improve Python Support

- src/DockWidget.cpp
- src/DockWidget.h
Hi @githubuser0xFFFF would it be possible to add this small change that allows user defined QAction to be used for toggling dock windows?
> Add ability to set user defined toggle view action

- src/DockContainerWidget.cpp
delete old root splitter layout item
> Fix memory leak in CDockContainerWidget::restoreState

- src/DockWidget.cpp
When requesting hide on a dockwidget that has been added to a dockmanager, but isn't yet visible, there was a creash. The crash has been fixed by moving the code to the existing guard check for the area.
> Fix DockWidget crach when area is a nullptr.

- src/DockAreaWidget.cpp
If a dockwidget has been manually deleted, the dockmanager would delete it again when deleting the area in its dtor. 
The 'optimal' solution would likely have been changing CDockWidget::~CDockWidget to add
if (d->DockArea) d->DockArea->removeDockWidget(this); (before delete d).
However, it is not trivial (for me) to conclude that such a change would be safe on program shutdown.
> Avoid dock manager double delete (crashes)

- src/DockAreaWidget.cpp
- src/DockContainerWidget.cpp
- src/DockFocusController.cpp
- src/DockManager.cpp
- src/DockWidget.cpp
Delete areas later so that that they can be accessed by (inherited) dock widgets in dtor. Add some QPointer to prevent crashes.
Hence allow users to do more while dock widgets etc are being destroyed.
> Improve safety in code

- src/DockAreaTitleBar_p.h
- src/DockManager.cpp
- src/DockWidget.cpp
- src/DockWidget.h
- src/DockWidgetTab.h
- src/ElidingLabel.h
- src/ads_globals.cpp
- src/linux/FloatingWidgetTitleBar.cpp
Avoid compiler warnings by using nullptr consistently.
> Fix 'zero as null pointer constant' warnings

- src/AutoHideDockContainer.h
- src/AutoHideSideBar.h
This PR fixes the forward declarations for `QXmlStreamWriter`.
> fix forward declarations of `QXmlStreamWriter`

- src/AutoHideTab.cpp
- src/DockAreaTitleBar.cpp
- src/DockWidgetTab.cpp
- src/FloatingDockContainer.cpp
- src/ads_globals.h
I like to build my projects with `CMAKE_UNITY_BUILD` enabled. However, a few ODR vialations prevent a unity build.
I changed the following things:
* move the `LocationProperty` to the `ads_globals.h` header
* use the `LocationProperty` for all `"Location"` strings
* rename `zOrderCounter` in `FloatingDockContainer.cpp`  to `zOrderCounterFloating`
> Fix ODR violations when using CMake unity builds.

- README.md
Removes an extra `the` in the Readme about the tested Linux versions
> readme: small wording improvements

- src/DockAreaTabBar.cpp
In some situation the singleShot timer crashes because of already deleted objects. A check of the pointers fixes that.
> Check if pointers used in singleShot timer are still valid

- src/CMakeLists.txt
For `CMAKE_INSTALL_*` variables introduced by #593 to be defined, CNUInstallDirs has to be included: https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html#module:GNUInstallDirs
> Include GNUInstallDirs for CMAKE_INSTALL_* vars to be defined

- src/FloatingDockContainer.h
Expose CFloatingDockContainer::startDragging as a public method to allow external code to initiate the dragging of floating dock containers. This enables users to programmatically initiate view drags, even from non-ADS widgets.
> Make CFloatingDockContainer::startDragging public

- src/DockAreaTabBar.cpp
- src/DockAreaTabBar.h
Remove custom wheelEvent handler. Default QAbstractScrollArea wheel handler seems to work better on platforms like MacOS.
Before:
https://github.com/user-attachments/assets/04c06c78-b0d3-4790-8b23-a96be8b4aa68
due to hardcoded step value, it is very difficult to scroll to the desired tab
After:
https://github.com/user-attachments/assets/aef90a12-8c10-4451-8e62-7af882ad13d1
> Improved tab bar scrolling

- demo/CMakeLists.txt
- examples/autohide/CMakeLists.txt
- examples/autohidedragndrop/CMakeLists.txt
- examples/centralwidget/CMakeLists.txt
- examples/configflags/CMakeLists.txt
- examples/deleteonclose/CMakeLists.txt
- examples/dockindock/CMakeLists.txt
- examples/emptydockarea/CMakeLists.txt
- examples/hideshow/CMakeLists.txt
- examples/sidebar/CMakeLists.txt
- examples/simple/CMakeLists.txt
- src/CMakeLists.txt
See issue https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/issues/682
This fixes the deployment issues with `windeployqt`.
```
$> cd build\x64\bin\Debug
$> windeployqt --dry-run --list mapping .\SimpleExample.exe
Unable to find dependent libraries of C:\Qt\6.6.3\msvc2019_64\bin\qt6advanceddockingd.dll :Cannot open 'C:/Qt/6.6.3/msvc2019_64/bin/qt6advanceddockingd.dll': The system cannot find the file specified.
```
```
$> cd build\x64\bin\Debug
$> windeployqt --dry-run --list mapping .\SimpleExample.exe
Adding in plugin type generic for module: Qt6Gui
Adding in plugin type iconengines for module: Qt6Gui
Adding in plugin type imageformats for module: Qt6Gui
Adding in plugin type networkinformation for module: Qt6Network
Adding in plugin type platforminputcontexts for module: …
```
> Fix issue with windeployqt

- README.md
- doc/user-guide.md
- src/DockAreaWidget.cpp
- src/DockComponentsFactory.h
- src/DockManager.cpp
- src/ads_globals.cpp
- src/ads_globals.h
Found via `codespell -q 3 -L te,ridiculus,varius`
There are several typos I didn't include that perhaps at a later date can be fixed. 
```
./demo/images/material_icons_license.txt:2: commerical ==> commercial
./src/DockAreaTitleBar.cpp:100: overlayed ==> overlaid
./src/DockOverlay.cpp:915: Offest ==> Offset
./src/DockOverlay.cpp:917: Offest ==> Offset
```
> Fix various typos

- CMakeLists.txt
- demo/CMakeLists.txt
- examples/CMakeLists.txt
- examples/autohide/CMakeLists.txt
- examples/autohidedragndrop/CMakeLists.txt
- examples/centralwidget/CMakeLists.txt
- examples/configflags/CMakeLists.txt
- examples/deleteonclose/CMakeLists.txt
- examples/dockindock/CMakeLists.txt
- examples/emptydockarea/CMakeLists.txt
- examples/hideshow/CMakeLists.txt
- examples/sidebar/CMakeLists.txt
- examples/simple/CMakeLists.txt
- src/CMakeLists.txt
When building with a current version of CMake this warning occures:
```
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 3.10 will be removed from a future version of
CMake.
Update the VERSION argument <min> value.  Or, use the <min>...<max>
syntax
to tell CMake that the project requires at least <min> but has been
updated
to work with policies introduced by <max> or earlier.
```
Since Qt 6 already [requires at least CMake 3.16](https://doc.qt.io/qt-6/cmake-supported-cmake-versions.html) (which was released in 2019), I have chosen this as the minimum version.
If this is not desired, at least the compatibility with this version (and the included policies) could be specified: `cmake_minimum_required(VERSION 3.5...3.16)`
> update minimum CMake version to 3.16

- src/DockWidget.cpp
This is essentially due to `setDockArea` undoing the earlier `setParent`.
> Fixed crash caused by unparented widgets after restoring layout

- src/DockAreaWidget.cpp
As proposed in discussion #719, the Title Bar should probably not be hidden if it contains any explicit set Actions. This would be a way to achieve this without further configuration switches.
> Always show TitleBar if it contains any explicit actions

- src/CMakeLists.txt
This was previously handled here:
if (UNIX AND NOT APPLE)
include_directories(${Qt${QT_VERSION_MAJOR}Gui_PRIVATE_INCLUDE_DIRS})
endif()
but it seems Qt is phasing this out in favor of explicit cmake targets added in Qt 6.
btw, my Ubunut 22.04 also needed the following libs after upgrading from 6.7.2:
sudo apt install libxkbcommon-dev libxkbfile-dev libxcb-xkb-dev
> fix compile with Qt 6.9.0 - qplatformnativeinterface.h missing

- src/AutoHideDockContainer.cpp
Would fix #739
Tested locally.  Results below
I am still unsure wether ``DockWidget::isAutoHide()`` should query the dockArea. 
Also, I find it a bit weird that the pointer is assigned by ``CAutoHideSideBar`` but removed by ``AutoHideDockContainer``. But looking at the call graph, every one calls the ``CAutoHideDockContainer::cleanupAndDelete`` function while ``CAutoHideSideBar.removeAutoHideWidget``  is only called when a tab moves from one sidebar to another.
> Remove dangling pointer to tab widget when removing an autohide widget
