githubuser0xFFFF/Qt-Advanced-Docking-System

- src/FloatingDockContainer.cpp
- src/FloatingDockContainer.h
Also std::cout were replaced with common used qDebug()
> DockWidgetClosable now prevents Floating Dock Windows from closing

- CMakeLists.txt
- demo/CMakeLists.txt
- example/CMakeLists.txt
- src/ads_globals.h
CMake has been announced as the build system of choice for Qt in the
future so it's useful to provide a project file for it
Also added the possibility to compile as a static library
> Added CMake project file

- src/DockAreaWidget.cpp
- src/DockContainerWidget.cpp
- src/DockContainerWidget.h
- src/DockManager.cpp
- src/DockManager.h
- src/DockWidget.cpp
- src/DockWidget.h
This pull request add support for removing docks during runtime.
> Feature: Remove docks

- CMakeLists.txt
Linux source files weren't included in CMakeLists.txt.
> adding linux src files to CMake

- src/DockAreaTabBar.cpp
- src/DockAreaTitleBar.cpp
- src/DockAreaWidget.cpp
- src/DockContainerWidget.cpp
- src/DockManager.cpp
- src/DockSplitter.cpp
- src/DockWidget.cpp
- src/DockWidgetTab.cpp
- src/FloatingDockContainer.cpp
- src/ads_globals.h
You can switch it on/off via defining ADS_DEBUG_PRINT in comipation settings on your build system.
By default massages wouldn't be printed.
> Make debug messages conditional.

- src/ElidingLabel.cpp
This is a fix for the existing/already merged pull request #44. It fixes the eliding labels issue on Windows.
> Fix PR #44

- src/DockAreaWidget.cpp
- src/DockContainerWidget.h
- src/DockManager.h
- src/DockWidgetTab.cpp
> Add option to always show all tabs

- demo/demo.py
- demo/status_dialog.py
- examples/sidebar/MainWindow.cpp
- examples/sidebar/sidebar.py
- setup.py
- sip/DockComponentsFactory.sip
- sip/DockManager.sip
- sip/DockWidgetTab.sip
- sip/ads_globals.sip
This PR is to update the SIP files from the PyQt bindings to match v3.4
> Update PyQt bindings

- .appveyor.yml
- .travis.yml
- CMakeLists.txt
- cmake/modules/GetGitRevisionDescription.cmake
- cmake/modules/GetGitRevisionDescription.cmake.in
- demo/CMakeLists.txt
- examples/CMakeLists.txt
- examples/deleteonclose/CMakeLists.txt
- examples/sidebar/CMakeLists.txt
- examples/simple/CMakeLists.txt
- src/CMakeLists.txt
- src/DockAreaTabBar.cpp
- src/DockComponentsFactory.cpp
- src/DockWidgetTab.cpp
- src/qtadvanceddockingConfig.cmake
- src/src.pro
> Modernised CMake build files and CI configs

- setup.py
- sip/DockAreaTitleBar_p.sip
- sip/DockAreaWidget.sip
- sip/DockManager.sip
- sip/FloatingDockContainer.sip
- sip/FloatingDragPreview.sip
- sip/ads.sip
- sip/ads_globals.sip
Thank you, @n-elie for the help with the Windows fix.
Closes #191
> FIX: Update Python bindings for 3.4.2 and current master.

- demo/MainWindow.cpp
- src/DockContainerWidget.cpp
Hi,
I have an application where I split an existing area in two. With this modifications it look much better ;)
See video here: https://vimeo.com/426505015
Actually, it would also be quite easy to animate such "split"... I tried on another branch if you might be interested to merge.
> Equal split on insertion

- setup.py
This add the hability to generate a Python stub file (pyi) to be used by linters.
This is working but implementation may be improved. I would like to hear from other Python contributors.
> Generate Python stubs file for linters

- demo/demo.py
- setup.py
- sip/DockManager.sip
- sip/DockWidget.sip
This PR seems to include already merged commits. Not a git expert here, I certainly messed up somewhere.
> Update Python bindings and demo to reflect recent changes

- demo/demo.py
- examples/deleteonclose/deleteonclose.py
- examples/simple/simple.py
- sip/DockAreaWidget.sip
- sip/DockManager.sip
- src/DockContainerWidget.h
- src/DockManager.h
- src/DockWidget.h
I had to modify the signals in headers to use the full namespace otherwise they are unusable in Python bindings
> Update Python bindings

- src/DockAreaWidget.cpp
- src/DockManager.cpp
A couple of errors that I found while trying to create and delete CDockWidget in code.
> Floating window fixes.

- src/DockAreaWidget.cpp
- src/DockManager.cpp
Sorry my first commit was buggy, I was in a hurry and didn't test the fix well.
> Memory leak

- src/DockAreaTabBar.cpp
- src/DockAreaTabBar.h
- src/DockAreaTitleBar.cpp
- src/DockAreaTitleBar.h
- src/DockAreaWidget.cpp
- src/DockAreaWidget.h
- src/DockContainerWidget.cpp
- src/DockFocusController.cpp
- src/DockFocusController.h
- src/DockManager.cpp
- src/DockWidget.cpp
- src/DockWidgetTab.cpp
- src/DockWidgetTab.h
- src/ElidingLabel.cpp
- src/ElidingLabel.h
- src/FloatingDragPreview.cpp
- src/FloatingDragPreview.h
This comit is an addtion to pull request #295. Not all Qt keywords were included.
> Additional Qt keyword conversion.

- src/DockManager.cpp
Fix https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/issues/307
> Fix memory leaks

- src/DockManager.cpp
> Fix addDockWidgetTab doesn't create tabbed area #415

- project.py
For PyQt bindings. This will help building the project on [conda-forge](https://github.com/conda-forge/pyqtads-feedstock/pull/45)
> Add options to project.py to specify include and library directories

- pyproject.toml
- sip/AutoHideDockContainer.sip
- sip/AutoHideSideBar.sip
- sip/AutoHideTab.sip
- sip/DockAreaTitleBar.sip
- sip/DockAreaWidget.sip
- sip/DockComponentsFactory.sip
- sip/DockContainerWidget.sip
- sip/DockFocusController.sip
- sip/DockManager.sip
- sip/DockWidget.sip
- sip/FloatingDockContainer.sip
- sip/FloatingDragPreview.sip
- sip/PushButton.sip
- sip/ResizeHandle.sip
- sip/ads.sip
- sip/ads_globals.sip
> Update python bindings to 4.0.2

- src/DockFocusController.cpp
- src/DockManager.cpp
- src/DockManager.h
- src/DockOverlay.cpp
- src/FloatingDockContainer.cpp
- src/FloatingDockContainer.h
- src/FloatingDragPreview.cpp
- src/ads_globals.cpp
- src/ads_globals.h
> Fix BSD build

- src/CMakeLists.txt
https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/issues/406
> CMake Script - Add debug postfix "d" (#406)

- examples/dockindock/main.cpp
- src/DockManager.cpp
Make sure area are only deleted if children of current dock manager
> Fix https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/issues/585

- src/ads_globals.h
Fix compiler warning about extra ";".
> Fix "extra ;" warning

- README.md
Hello @githubuser0xFFFF and other authors.   Thanks for this incredible package.
I took the liberty to update the bindings for PyQt6, and have put them on pypi: https://pypi.org/project/PyQt6Ads/ (I hope you don't mind!)
this PR mentions it in the readme, if you'd like to include it.
> Mention pyqt6 bindings in readme
